apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::068703216520:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DLHLZ9CI8TMO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::068703216520:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-21T00:14:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "781"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 09011a33-8365-11ea-9ed0-0a402a4377eb
